server:
  port: 8082

spring:
  application:
    name: bff

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bff
            client-secret: ${BFF_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/keycloak
            scope: openid,profile,email

        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/spring-backend-lab

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

springdoc:
  swagger-ui:
    csrf:
      enabled: true
      cookie-name: XSRF-TOKEN
      header-name: X-XSRF-TOKEN

app:
  backend:
    url: http://localhost:8080